# ============================================
# EMAIL_SENDER.PY - MINERVINI SCREENER v6.3
# Dengan Chart Patterns & Hanya 8/8
# ============================================

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from datetime import datetime, timezone, timedelta

def get_wib_time():
    """
    Mendapatkan waktu WIB (UTC+7) yang akurat
    """
    utc_now = datetime.now(timezone.utc)
    wib_now = utc_now + timedelta(hours=7)
    return wib_now

def send_email_report(df, email_to, email_from, password, criteria, smtp_server='smtp.gmail.com', port=587):
    """
    Mengirim laporan hasil screening ke email - HANYA 8/8
    """
    print("\n" + "=" * 50)
    print("📧 PROSES KIRIM EMAIL")
    print("=" * 50)
    
    wib_time = get_wib_time()
    
    try:
        msg = MIMEMultipart()
        msg['From'] = email_from
        msg['To'] = email_to
        msg['Subject'] = f"📊 Minervini Screener 8/8 - {wib_time.strftime('%d/%m/%Y %H:%M')} WIB"
        
        if df is not None and not df.empty:
            total_8 = len(df)
            
            # Buat tabel HTML
            table_html = df.to_html(index=False, escape=False, classes='screening-table')
            
            # Buat body email
            body = f"""
            <html>
            <head>
                <style>
                    body {{ 
                        font-family: 'Segoe UI', Arial, sans-serif; 
                        margin: 20px; 
                        color: #333;
                        background-color: #f5f5f5;
                    }}
                    .container {{
                        max-width: 1200px;
                        margin: 0 auto;
                        background-color: white;
                        padding: 25px;
                        border-radius: 15px;
                        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
                    }}
                    h2 {{ 
                        color: #2c3e50; 
                        border-bottom: 3px solid #3498db; 
                        padding-bottom: 10px;
                        margin-top: 0;
                    }}
                    .summary-box {{
                        background: linear-gradient(135deg, #27ae60 0%, #2ecc71 100%);
                        color: white;
                        padding: 20px;
                        border-radius: 10px;
                        margin: 20px 0;
                    }}
                    table {{ 
                        border-collapse: collapse; 
                        width: 100%;
                        margin: 20px 0;
                        font-size: 13px;
                        background-color: white;
                        border-radius: 10px;
                        overflow: hidden;
                        box-shadow: 0 2px 3px rgba(0,0,0,0.1);
                    }}
                    th {{ 
                        background-color: #3498db; 
                        color: white; 
                        padding: 12px;
                        text-align: left;
                    }}
                    td {{ 
                        border: 1px solid #ddd; 
                        padding: 8px; 
                    }}
                    tr:nth-child(even) {{ 
                        background-color: #f8f9fa; 
                    }}
                    .badge-8 {{
                        background-color: #27ae60;
                        color: white;
                        padding: 3px 10px;
                        border-radius: 15px;
                        font-weight: bold;
                        display: inline-block;
                    }}
                    .footer {{
                        margin-top: 30px;
                        padding-top: 15px;
                        border-top: 1px solid #eee;
                        text-align: center;
                        color: #7f8c8d;
                        font-size: 12px;
                    }}
                </style>
            </head>
            <body>
                <div class="container">
                    <h2>📈 MINERVINI SCREENER - HASIL 8/8</h2>
                    <p><strong>Waktu Screening:</strong> {wib_time.strftime('%d-%m-%Y %H:%M:%S')} WIB</p>
                    
                    <div class="summary-box">
                        <h3 style="color: white; margin-top: 0;">📊 RINGKASAN</h3>
                        <p style="font-size: 24px; margin: 10px 0;">Total Saham 8/8: <strong>{total_8}</strong></p>
                    </div>
                    
                    <h3>📋 DETAIL SAHAM 8/8</h3>
                    {table_html}
                    
                    <div class="footer">
                        <p><i>Hanya saham dengan 8/8 kriteria Minervini yang ditampilkan.</i></p>
                        <p>Generated by Minervini Screener v6.3 • {wib_time.strftime('%d-%m-%Y %H:%M:%S')} WIB</p>
                    </div>
                </div>
            </body>
            </html>
            """
            
            # Lampirkan CSV
            csv_data = df.to_csv(index=False)
            attachment = MIMEApplication(csv_data.encode('utf-8'))
            attachment.add_header(
                'Content-Disposition', 'attachment', 
                filename=f"minervini_88_{wib_time.strftime('%Y%m%d_%H%M')}.csv"
            )
            msg.attach(attachment)
            
        else:
            # Email ketika tidak ada hasil 8/8
            body = f"""
            <html>
            <body>
                <div style="font-family: Arial; max-width: 600px; margin: 0 auto; padding: 20px;">
                    <h2>📈 MINERVINI SCREENER</h2>
                    <p><strong>Waktu:</strong> {wib_time.strftime('%d-%m-%Y %H:%M:%S')} WIB</p>
                    <div style="background-color: #f8d7da; padding: 20px; border-radius: 10px;">
                        <h3>📭 TIDAK ADA SAHAM 8/8</h3>
                        <p>Tidak ditemukan saham yang memenuhi semua 8 kriteria Minervini pada screening kali ini.</p>
                    </div>
                </div>
            </body>
            </html>
            """
        
        msg.attach(MIMEText(body, 'html'))
        
        # Kirim email
        print(f"📤 Menghubungi server {smtp_server}:{port}...")
        server = smtplib.SMTP(smtp_server, port)
        server.starttls()
        server.login(email_from, password)
        server.send_message(msg)
        server.quit()
        
        print("✅ EMAIL BERHASIL DIKIRIM!")
        return True
        
    except Exception as e:
        print(f"❌ GAGAL KIRIM EMAIL: {e}")
        return False
